
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    mvc.pathmatch.matching-strategy: ant_path_matcher

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true


